ARCHS = armv7 armv7s arm64
include theos/makefiles/common.mk

BUNDLE_NAME = OnlyOneNotificationFlipswitch
OnlyOneNotificationFlipswitch_FILES = Switch.x
OnlyOneNotificationFlipswitch_FRAMEWORKS = UIKit
OnlyOneNotificationFlipswitch_LIBRARIES = flipswitch
OnlyOneNotificationFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
